#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = HardZinc

# --------------------------------------------------------------
# Files to build

FILES_DSP = \
	DistrhoPluginHardZinc.cpp

# --------------------------------------------------------------
# Do some magic

include ../../dpf/Makefile.plugins.mk

# --------------------------------------------------------------
# Enable all possible plugin types

all: clap dssi_dsp lv2_dsp vst2 vst3

# --------------------------------------------------------------
